# Generated by Django 3.0.6 on 2020-05-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200527_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='Kyiv', max_length=64),
            preserve_default=False,
        ),
    ]
